const express = require('express');
const fs = require('fs');
const path = require('path');
const db = require('./db');
const https = require('https');
const querystring = require('querystring');
const config = require('./config');
const crypto = require('crypto');
const supabaseState = require('./supabase/state');

const app = express();
const sessions = new Map();
const revokedSessions = new Set();
const googleTokens = new Map();
const PORT = process.env.PORT || 4173;
const DATA_FILE = path.join(__dirname, 'data.json');
const APP_ROOT = fs.existsSync(path.join(__dirname, 'index.html')) ? __dirname : path.join(__dirname, '..');
app.use(express.json());
app.use(express.static(APP_ROOT));
app.get('/', (req, res) => res.sendFile(path.join(APP_ROOT, 'index.html')));
app.get(['/login', '/register', '/forgot-password'], (req, res) => res.sendFile(path.join(APP_ROOT, 'auth.html')));
app.get('/book/:slug', (req, res) => res.sendFile(path.join(APP_ROOT, 'booking.html')));

const seed = {
  users: [{ id: 'owner', email: 'ahmed@example.com', password: 'demo', name: 'أحمد الشمري' }],
  profile: { name: 'أحمد الشمري', title: 'Product Manager', location: 'Riyadh, Saudi Arabia', bio: 'أساعد الفرق على بناء منتجات أفضل.', photo: '👨🏻‍💼', timezone: 'Asia/Riyadh' },
  integrations: { googleCalendar: false, googleMeet: false, outlook: false, zoom: false },
  meetingTypes: [
    { id: 'intro', name: 'استشارة عبر الفيديو', en: 'Intro video call', duration: 30, color: '#2166f3', mode: 'Google Meet' },
    { id: 'strategy', name: 'جلسة استراتيجية', en: 'Strategy session', duration: 60, color: '#15a66b', mode: 'Zoom' }
  ],
  availability: { sunday: '09:00–18:00', monday: '09:00–18:00', tuesday: '09:00–18:00', wednesday: '09:00–18:00', thursday: '09:00–15:00', friday: 'Prayer time protected', saturday: '09:00–18:00' },
  bookings: []
};
function readData() { try { return JSON.parse(fs.readFileSync(DATA_FILE, 'utf8')); } catch { fs.writeFileSync(DATA_FILE, JSON.stringify(seed, null, 2)); return structuredClone(seed); } }
function writeData(d) { fs.writeFileSync(DATA_FILE, JSON.stringify(d, null, 2)); }
db.init(seed);
function readData() { return db.read(); }
function writeData(d) { db.write(d); }
function bookingOverlaps(d, candidateDate, candidateTime, candidateDuration, ignoreId) { const start = Number(candidateTime.slice(0,2))*60 + Number(candidateTime.slice(3)); const end = start + candidateDuration + Number(d.bookingRules?.bufferMinutes || 0); return d.bookings.some(existing => { if (existing.id === ignoreId || existing.status === 'cancelled' || existing.date !== candidateDate) return false; const type = d.meetingTypes.find(x => x.id === existing.meetingTypeId); const existingStart = Number(existing.time.slice(0,2))*60 + Number(existing.time.slice(3)); const existingEnd = existingStart + Number(type?.duration || 30) + Number(d.bookingRules?.bufferMinutes || 0); return start < existingEnd && existingStart < end; }); }
function bookingOutsideRules(d, date, time) { const rules = d.bookingRules || { minimumNoticeMinutes: 60, maximumDaysAhead: 60 }; const today = new Date(); const slot = new Date(`${date}T${time}:00`); const startOfToday = new Date(`${today.toISOString().slice(0,10)}T00:00:00`); const requestedDay = new Date(`${date}T00:00:00`); const daysAhead = Math.floor((requestedDay - startOfToday) / 86400000); return slot.getTime() - today.getTime() < Number(rules.minimumNoticeMinutes || 0) * 60000 || daysAhead > Number(rules.maximumDaysAhead || 60) || daysAhead < 0; }
function hashPassword(password) { const salt = crypto.randomBytes(16).toString('hex'); const hash = crypto.scryptSync(password, salt, 64).toString('hex'); return `scrypt$${salt}$${hash}`; }
function verifyPassword(password, stored) { if (!stored?.startsWith('scrypt$')) return stored === password; const [, salt, hash] = stored.split('$'); const actual = crypto.scryptSync(password, salt, 64).toString('hex'); return crypto.timingSafeEqual(Buffer.from(actual, 'hex'), Buffer.from(hash, 'hex')); }
function cookieValue(req, name) { const raw = req.headers.cookie || ''; const item = raw.split(';').map(x => x.trim()).find(x => x.startsWith(`${name}=`)); return item ? decodeURIComponent(item.slice(name.length + 1)) : null; }
function sessionToken(userId) { const payload = `${userId}.${Date.now()}`; const signature = crypto.createHmac('sha256', config.sessionSecret).update(payload).digest('hex'); return `${payload}.${signature}`; }
function sessionUser(token) { const parts = String(token || '').split('.'); if (parts.length !== 3) return null; const [userId, issued, signature] = parts; if (!userId || !/^\d+$/.test(issued) || Date.now() - Number(issued) > 604800000) return null; const expected = crypto.createHmac('sha256', config.sessionSecret).update(`${userId}.${issued}`).digest('hex'); return signature.length === expected.length && crypto.timingSafeEqual(Buffer.from(signature), Buffer.from(expected)) ? userId : null; }
function currentUser(req) { const token = cookieValue(req, 'calpro_session'); if (!token || revokedSessions.has(token)) return null; return sessions.get(token) || sessionUser(token); }
function requireAuth(req, res, next) { const userId = currentUser(req); if (!userId) return res.status(401).json({ error: 'Authentication required.' }); req.userId = userId; next(); }
const authAttempts = new Map();
app.use('/api/auth', (req, res, next) => { const key = req.ip || 'local'; const now = Date.now(); const recent = (authAttempts.get(key) || []).filter(t => now - t < 60000); if (recent.length >= 20) return res.status(429).json({ error: 'Too many authentication attempts. Try again later.' }); recent.push(now); authAttempts.set(key, recent); next(); });
function httpsRequest(url, options, body) { return new Promise((resolve, reject) => { const request = https.request(url, { method: options.method || 'GET', headers: options.headers || {} }, response => { let data=''; response.on('data', chunk => data += chunk); response.on('end', () => { try { resolve({ status: response.statusCode, body: JSON.parse(data) }); } catch { reject(new Error('Invalid OAuth provider response.')); } }); }); request.on('error', reject); if (body) request.write(body); request.end(); }); }
async function refreshGoogleToken(userId, token) { if (!token?.refresh_token) return token; const body = querystring.stringify({ client_id: config.googleClientId, client_secret: config.googleClientSecret, refresh_token: token.refresh_token, grant_type: 'refresh_token' }); const refreshed = await httpsRequest('https://oauth2.googleapis.com/token', { method: 'POST', headers: { 'Content-Type': 'application/x-www-form-urlencoded', 'Content-Length': Buffer.byteLength(body) } }, body); if (refreshed.status >= 400) return token; const next = { ...token, ...refreshed.body, refresh_token: token.refresh_token, received_at: Date.now() }; googleTokens.set(userId, next); db.saveOAuthToken(userId, 'google', next, config.tokenEncryptionKey); return next; }
async function googleCalendarRequest(userId, url) { let token = googleTokens.get(userId) || db.getOAuthToken(userId, 'google', config.tokenEncryptionKey); if (!token?.access_token) return null; if (!token.received_at) { token.received_at = Date.now(); db.saveOAuthToken(userId, 'google', token, config.tokenEncryptionKey); } if (token.expires_in && Date.now() > token.received_at + (token.expires_in - 60) * 1000) token = await refreshGoogleToken(userId, token); googleTokens.set(userId, token); return httpsRequest(url, { headers: { Authorization: `Bearer ${token.access_token}` } }); }
async function googleCalendarCreate(userId, booking, type, timezone) { const token = googleTokens.get(userId) || db.getOAuthToken(userId, 'google', config.tokenEncryptionKey); if (!token?.access_token) return null; const start = `${booking.date}T${booking.time}:00`; const endMinutes = Number(booking.time.slice(0,2)) * 60 + Number(booking.time.slice(3)) + Number(type?.duration || 30); const end = `${booking.date}T${String(Math.floor(endMinutes / 60)).padStart(2,'0')}:${String(endMinutes % 60).padStart(2,'0')}:00`; const payload = JSON.stringify({ summary: `${type?.en || 'Meeting'} · ${booking.name}`, description: `Guest email: ${booking.email}${booking.notes ? `\nNotes: ${booking.notes}` : ''}`, start: { dateTime: start, timeZone: timezone || 'Asia/Riyadh' }, end: { dateTime: end, timeZone: timezone || 'Asia/Riyadh' }, conferenceData: { createRequest: { requestId: crypto.randomUUID(), conferenceSolutionKey: { type: 'hangoutsMeet' } } } }); const result = await httpsRequest('https://www.googleapis.com/calendar/v3/calendars/primary/events?conferenceDataVersion=1', { method: 'POST', headers: { Authorization: `Bearer ${token.access_token}`, 'Content-Type': 'application/json', 'Content-Length': Buffer.byteLength(payload) } }, payload); if (result.status >= 400) throw new Error('Google Calendar event creation failed.'); return result.body;
}
async function googleCalendarChange(userId, eventId, method, payload = null) { const token = googleTokens.get(userId) || db.getOAuthToken(userId, 'google', config.tokenEncryptionKey); if (!token?.access_token || !eventId) return null; const body = payload ? JSON.stringify(payload) : null; const result = await httpsRequest(`https://www.googleapis.com/calendar/v3/calendars/primary/events/${encodeURIComponent(eventId)}`, { method, headers: { Authorization: `Bearer ${token.access_token}`, ...(body ? { 'Content-Type': 'application/json', 'Content-Length': Buffer.byteLength(body) } : {}) } }, body); if (result.status >= 400) throw new Error('Google Calendar update failed.'); return result.body;
}

app.use(async (req, res, next) => {
  if (!config.useSupabase || (req.method === 'GET' && !['/api/auth/google', '/api/auth/google/callback'].includes(req.path))) return next();
  const client = require('./supabase/client');
  try {
    const authPath = req.path.startsWith('/api/auth/');
    const owner = authPath ? null : await supabaseState.ownerProfile();
    if (config.useSupabase && req.path === '/api/auth/google' && req.method === 'GET') {
      const redirectTo = `${req.protocol}://${req.get('host')}/api/auth/google/callback`;
      const { url } = client.supabaseAuthConfig();
      return res.redirect(`${url}/auth/v1/authorize?provider=google&redirect_to=${encodeURIComponent(redirectTo)}`);
    }
    if (config.useSupabase && req.path === '/api/auth/google/callback' && req.method === 'GET') {
      if (!req.query.code) return res.status(400).send('Missing Supabase OAuth code.');
      const auth = await client.authExchange(req.query.code);
      if (!auth.user?.id) return res.status(502).send('Google sign-in did not return a user.');
      const token = sessionToken(auth.user.id); sessions.set(token, auth.user.id);
      const existing = await client.list('profiles', `?id=eq.${encodeURIComponent(auth.user.id)}&select=id`);
      if (!existing.length) await client.insert('profiles', { id: auth.user.id, name: auth.user.user_metadata?.full_name || auth.user.email || 'Mawaeedy user', timezone: 'Asia/Riyadh' });
      res.setHeader('Set-Cookie', `calpro_session=${token}; HttpOnly; SameSite=Lax; Path=/; Max-Age=604800`);
      return res.redirect('/');
    }
    if (req.path === '/api/auth/register' && req.method === 'POST') {
      const { email, password, name } = req.body || {};
      if (!email || !password || !name) return res.status(400).json({ error: 'Name, email, and password are required.' });
      const auth = await client.authRequest('signup', { email, password, data: { name } });
      if (auth.user?.id) await client.insert('profiles', { id: auth.user.id, name, timezone: 'Asia/Riyadh', slug: `${String(name).toLowerCase().replace(/[^a-z0-9]+/g, '-').replace(/^-|-$/g, '') || 'user'}-${String(auth.user.id).slice(0, 8)}` });
      return res.status(201).json({ id: auth.user?.id, email: auth.user?.email || email, name });
    }
    if (req.path === '/api/auth/login' && req.method === 'POST') {
      const { email, password } = req.body || {};
      if (!email || !password) return res.status(400).json({ error: 'Email and password are required.' });
      const auth = await client.authRequest('token?grant_type=password', { email, password });
      const userId = auth.user?.id;
      if (!userId) return res.status(401).json({ error: 'Invalid email or password.' });
      const token = sessionToken(userId); sessions.set(token, userId);
      res.setHeader('Set-Cookie', `calpro_session=${token}; HttpOnly; SameSite=Lax; Path=/; Max-Age=604800`);
      return res.json({ ok: true, user: { id: userId, email: auth.user.email, name: auth.user.user_metadata?.name || auth.user.email } });
    }
    if (req.path === '/api/auth/me' && req.method === 'GET') {
      const userId = currentUser(req); if (!userId) return res.status(401).json({ error: 'Authentication required.' });
      const profile = await client.list('profiles', `?id=eq.${encodeURIComponent(userId)}&select=*`);
      return res.json({ user: { id: userId, email: profile[0]?.email || '', name: profile[0]?.name || '' }, profile: profile[0] || null });
    }
    if (!owner?.id) return res.status(503).json({ error: 'No Supabase scheduling profile is configured.' });
    if (req.path === '/api/profile' && req.method === 'PUT') {
      if (!currentUser(req)) return res.status(401).json({ error: 'Authentication required.' });
      const body = req.body || {};
      const rows = await client.update('profiles', { name: body.name, photo: body.photo, bio: body.bio, job_title: body.title || body.job_title, timezone: body.timezone, slug: body.slug }, `?id=eq.${encodeURIComponent(owner.id)}`);
      return res.json(rows[0] || body);
    }
    if (req.path === '/api/availability' && req.method === 'PUT') {
      if (!currentUser(req)) return res.status(401).json({ error: 'Authentication required.' });
      const body = req.body || {};
      await client.remove('availability_rules', `?owner_id=eq.${encodeURIComponent(owner.id)}`);
      for (const [day, hours] of Object.entries(body)) {
        if (!/^\d{2}:\d{2}[–-]\d{2}:\d{2}$/.test(String(hours))) continue;
        const [start_time, end_time] = String(hours).split(/[–-]/);
        const day_of_week = ['sunday','monday','tuesday','wednesday','thursday','friday','saturday'].indexOf(day);
        if (day_of_week >= 0) await client.insert('availability_rules', { owner_id: owner.id, day_of_week, start_time, end_time, label: null, enabled: true });
      }
      return res.json(body);
    }
    if (req.path === '/api/meeting-types' && req.method === 'POST') {
      if (!currentUser(req)) return res.status(401).json({ error: 'Authentication required.' });
      const body = req.body || {};
      const rows = await client.insert('meeting_types', { owner_id: owner.id, name_ar: body.name || 'اجتماع جديد', name_en: body.en || 'New meeting', duration_minutes: Number(body.duration) || 30, color: body.color || '#2166f3', mode: body.mode || 'Google Meet' });
      const row = rows[0];
      return res.status(201).json({ id: row.id, supabaseId: row.id, name: row.name_ar, en: row.name_en, duration: row.duration_minutes, color: row.color, mode: row.mode });
    }
    next();
  } catch (error) { return res.status(503).json({ error: 'Unable to save data to Supabase.', detail: error.message }); }
});
app.get('/api/state', async (req, res) => { try { if (config.useSupabase) { const d = await supabaseState.publicState(); if (!currentUser(req)) return res.json(d); return res.json({ ...d, bookings: [] }); } const d = readData(); if (!currentUser(req)) return res.json({ profile: d.profile, meetingTypes: d.meetingTypes, availability: d.availability, integrations: d.integrations, bookings: [] }); res.json(d); } catch (error) { res.status(503).json({ error: 'Supabase state is unavailable.', detail: error.message }); } });
app.get('/api/health', (req, res) => { const d = readData(); res.json({ status: 'ok', service: 'calpro', database: 'connected', googleCalendar: Boolean(d.integrations?.googleCalendar), timestamp: new Date().toISOString() }); });
app.get('/api/public/:slug', (req, res) => { const d = readData(); const slug = d.profile.slug || 'ahmed'; if (req.params.slug !== slug) return res.status(404).json({ error: 'Scheduling profile not found.' }); res.json({ slug, profile: d.profile, meetingTypes: d.meetingTypes, availability: d.availability, timezone: d.profile.timezone }); });
app.get('/api/team', requireAuth, (req, res) => { const d = readData(); res.json(d.teamMembers || []); });
app.post('/api/team/invite', requireAuth, (req, res) => { const d = readData(); const { email, name, role } = req.body || {}; if (!email) return res.status(400).json({ error: 'Email is required.' }); d.teamMembers = d.teamMembers || []; if (d.teamMembers.some(m => m.email === email)) return res.status(409).json({ error: 'This member is already invited.' }); const member = { id: Date.now().toString(), email, name: name || email, role: role || 'member', status: 'invited', invitedAt: new Date().toISOString() }; d.teamMembers.push(member); writeData(d); res.status(201).json(member); });
app.get('/api/notifications', requireAuth, (req, res) => { const d = readData(); res.json((d.notifications || []).slice().reverse()); });
app.post('/api/notifications', requireAuth, (req, res) => { const d = readData(); const { channel, recipient, type, bookingId, message } = req.body || {}; if (!channel || !recipient || !type || !message) return res.status(400).json({ error: 'Channel, recipient, type, and message are required.' }); const item = { id: Date.now().toString(), channel, recipient, type, bookingId: bookingId || null, message, status: 'queued', createdAt: new Date().toISOString() }; d.notifications = d.notifications || []; d.notifications.push(item); writeData(d); res.status(201).json(item); });
app.get('/api/booking-rules', (req, res) => { const d = readData(); res.json(d.bookingRules || { minimumNoticeMinutes: 60, maximumDaysAhead: 60, bufferMinutes: 0 }); });
app.put('/api/booking-rules', requireAuth, (req, res) => { const d = readData(); const body = req.body || {}; d.bookingRules = { minimumNoticeMinutes: Math.max(0, Number(body.minimumNoticeMinutes) || 0), maximumDaysAhead: Math.max(1, Number(body.maximumDaysAhead) || 60), bufferMinutes: Math.max(0, Number(body.bufferMinutes) || 0) }; writeData(d); res.json(d.bookingRules); });
app.post('/api/auth/register', (req, res) => { const d = readData(); const { email, password, name } = req.body || {}; if (!email || !password || !name) return res.status(400).json({ error: 'Name, email, and password are required.' }); if (d.users.some(u => u.email === email)) return res.status(409).json({ error: 'An account with this email already exists.' }); const user = { id: Date.now().toString(), email, password: hashPassword(password), name }; d.users.push(user); writeData(d); res.status(201).json({ id: user.id, email: user.email, name: user.name }); });
app.post('/api/auth/login', (req, res) => { const d = readData(); const { email, password } = req.body || {}; const user = d.users.find(u => u.email === email); if (!user || !verifyPassword(password, user.password)) return res.status(401).json({ error: 'Invalid email or password.' }); if (!user.password.startsWith('scrypt$')) { user.password = hashPassword(password); writeData(d); } const token = sessionToken(user.id); sessions.set(token, user.id); res.setHeader('Set-Cookie', `calpro_session=${token}; HttpOnly; SameSite=Lax; Path=/; Max-Age=604800`); res.json({ ok: true, user: { id: user.id, email: user.email, name: user.name } }); });
app.post('/api/auth/logout', (req, res) => { const token = cookieValue(req, 'calpro_session'); if (token) { sessions.delete(token); revokedSessions.add(token); } res.setHeader('Set-Cookie', 'calpro_session=; HttpOnly; SameSite=Lax; Path=/; Max-Age=0'); res.json({ ok: true }); });
app.get('/api/auth/me', requireAuth, (req, res) => { const user = readData().users.find(u => u.id === req.userId); res.json({ user: { id: user.id, email: user.email, name: user.name } }); });
app.get('/api/auth/google', (req, res) => { if (!config.googleClientId) return res.status(503).send('Google OAuth is not configured.'); const params = new URLSearchParams({ client_id: config.googleClientId, redirect_uri: config.googleRedirectUri, response_type: 'code', scope: 'openid email profile https://www.googleapis.com/auth/calendar', access_type: 'offline', prompt: 'consent' }); res.redirect(`https://accounts.google.com/o/oauth2/v2/auth?${params}`); });
app.get('/api/auth/google/callback', async (req, res) => { try { if (!req.query.code) return res.status(400).send('Missing Google authorization code.'); const body = querystring.stringify({ code: req.query.code, client_id: config.googleClientId, client_secret: config.googleClientSecret, redirect_uri: config.googleRedirectUri, grant_type: 'authorization_code' }); const token = await httpsRequest('https://oauth2.googleapis.com/token', { method: 'POST', headers: { 'Content-Type': 'application/x-www-form-urlencoded', 'Content-Length': Buffer.byteLength(body) } }, body); if (token.status >= 400) return res.status(502).send('Google token exchange failed.'); const profile = await httpsRequest('https://openidconnect.googleapis.com/v1/userinfo', { headers: { Authorization: `Bearer ${token.body.access_token}` } }); if (profile.status >= 400) return res.status(502).send('Google profile lookup failed.'); const d = readData(); let user = d.users.find(u => u.email === profile.body.email); if (!user) { user = { id: `google_${Date.now()}`, email: profile.body.email, password: '', name: profile.body.name || profile.body.email }; d.users.push(user); } googleTokens.set(user.id, token.body); db.saveOAuthToken(user.id, 'google', token.body, config.tokenEncryptionKey); d.integrations.googleCalendar = true; d.integrations.googleMeet = true; writeData(d); const session = crypto.randomBytes(32).toString('hex'); sessions.set(session, user.id); res.setHeader('Set-Cookie', `calpro_session=${session}; HttpOnly; SameSite=Lax; Path=/; Max-Age=604800`); res.redirect('/'); } catch (error) { res.status(502).send(`Google OAuth error: ${error.message}`); } });
app.get('/api/calendar/google/events', requireAuth, async (req, res) => { try { const result = await googleCalendarRequest(req.userId, 'https://www.googleapis.com/calendar/v3/calendars/primary/events?singleEvents=true&orderBy=startTime&maxResults=50'); if (!result) return res.status(409).json({ error: 'Google Calendar is not connected.' }); if (result.status >= 400) return res.status(502).json({ error: 'Google Calendar request failed.' }); res.json({ events: result.body.items || [] }); } catch (error) { res.status(502).json({ error: error.message }); } });
app.post('/api/calendar/google/events', requireAuth, async (req, res) => { try { const token = googleTokens.get(req.userId); if (!token?.access_token) return res.status(409).json({ error: 'Google Calendar is not connected.' }); const { summary, start, end, timezone } = req.body || {}; if (!summary || !start || !end) return res.status(400).json({ error: 'Summary, start, and end are required.' }); const payload = JSON.stringify({ summary, start: { dateTime: start, timeZone: timezone || 'Asia/Riyadh' }, end: { dateTime: end, timeZone: timezone || 'Asia/Riyadh' }, conferenceData: { createRequest: { requestId: crypto.randomUUID(), conferenceSolutionKey: { type: 'hangoutsMeet' } } } }); const result = await httpsRequest('https://www.googleapis.com/calendar/v3/calendars/primary/events?conferenceDataVersion=1', { method: 'POST', headers: { Authorization: `Bearer ${token.access_token}`, 'Content-Type': 'application/json', 'Content-Length': Buffer.byteLength(payload) } }, payload); if (result.status >= 400) return res.status(502).json({ error: 'Google Calendar event creation failed.' }); res.status(201).json({ event: result.body }); } catch (error) { res.status(502).json({ error: error.message }); } });
app.post('/api/bookings/:id/publish-to-google', requireAuth, async (req, res) => { const booking = readData().bookings.find(x => x.id === req.params.id); if (!booking) return res.status(404).json({ error: 'Booking not found.' }); const type = readData().meetingTypes.find(x => x.id === booking.meetingTypeId); const start = `${booking.date}T${booking.time}:00`; const endMinutes = Number(booking.time.slice(0,2)) * 60 + Number(booking.time.slice(3)) + (type?.duration || 30); const end = `${booking.date}T${String(Math.floor(endMinutes/60)).padStart(2,'0')}:${String(endMinutes%60).padStart(2,'0')}:00`; const token = googleTokens.get(req.userId); if (!token?.access_token) return res.status(409).json({ error: 'Google Calendar is not connected.' }); const payload = JSON.stringify({ summary: `${type?.en || 'Meeting'} · ${booking.name}`, description: `Guest email: ${booking.email}`, start: { dateTime: start, timeZone: 'Asia/Riyadh' }, end: { dateTime: end, timeZone: 'Asia/Riyadh' }, conferenceData: { createRequest: { requestId: crypto.randomUUID(), conferenceSolutionKey: { type: 'hangoutsMeet' } } } }); const result = await httpsRequest('https://www.googleapis.com/calendar/v3/calendars/primary/events?conferenceDataVersion=1', { method: 'POST', headers: { Authorization: `Bearer ${token.access_token}`, 'Content-Type': 'application/json', 'Content-Length': Buffer.byteLength(payload) } }, payload); if (result.status >= 400) return res.status(502).json({ error: 'Google Calendar event creation failed.' }); res.status(201).json({ bookingId: booking.id, event: result.body }); });
app.get('/api/private/profile', requireAuth, (req, res) => { const d = readData(); res.json({ user: d.users.find(u => u.id === req.userId), profile: d.profile }); });
app.post('/api/auth/reset-password', (req, res) => { const d = readData(); const { email, password } = req.body || {}; const user = d.users.find(u => u.email === email); if (!user) return res.status(404).json({ error: 'No account found for this email.' }); if (!password) return res.status(400).json({ error: 'A new password is required.' }); user.password = hashPassword(password); writeData(d); res.json({ ok: true }); });
app.put('/api/profile', requireAuth, (req, res) => { const d = readData(); const next = { ...d.profile, ...req.body }; if (next.slug !== undefined && !/^[a-z0-9](?:[a-z0-9-]{0,38}[a-z0-9])?$/.test(String(next.slug))) return res.status(400).json({ error: 'Booking URL must use lowercase letters, numbers, and hyphens only.' }); d.profile = next; writeData(d); res.json(d.profile); });
app.put('/api/availability', requireAuth, (req, res) => { const d = readData(); d.availability = { ...d.availability, ...req.body }; writeData(d); res.json(d.availability); });
app.get('/api/availability/slots', (req, res) => { const d = readData(); const date = String(req.query.date || ''); if (!/^\d{4}-\d{2}-\d{2}$/.test(date)) return res.status(400).json({ error: 'A date in YYYY-MM-DD format is required.' }); const day = new Date(`${date}T12:00:00Z`).getUTCDay(); const dayKey = ['sunday','monday','tuesday','wednesday','thursday','friday','saturday'][day]; const hours = d.availability[dayKey] || '09:00–18:00'; if (hours === 'مغلق' || dayKey === 'friday' && hours === 'Prayer time protected') return res.json({ date, timezone: d.profile.timezone, slots: [] }); const rules = d.bookingRules || { minimumNoticeMinutes: 60, maximumDaysAhead: 60, bufferMinutes: 0 }; const today = new Date(); const requestedDay = new Date(`${date}T23:59:59`); const daysAhead = Math.ceil((new Date(`${date}T12:00:00`) - new Date(`${today.toISOString().slice(0,10)}T12:00:00`)) / 86400000); if (daysAhead > Number(rules.maximumDaysAhead || 60)) return res.json({ date, day: dayKey, workingHours: hours, timezone: d.profile.timezone, slots: [], reason: 'outside-booking-window' }); const blocked = d.bookings.filter(b => b.status !== 'cancelled' && b.date === date).map(b => { const start = Number(b.time.slice(0,2))*60 + Number(b.time.slice(3)); return [start, start + Number(rules.bufferMinutes || 0)]; }); const slots = ['09:00','09:30','10:00','10:30','11:00','11:30','12:00','12:30','13:00','13:30','14:00','14:30','15:00','15:30','16:00','16:30','17:00','17:30'].filter(t => { const minutes = Number(t.slice(0,2))*60 + Number(t.slice(3)); const slotDate = new Date(`${date}T${t}:00`); const tooSoon = slotDate.getTime() - today.getTime() < Number(rules.minimumNoticeMinutes || 0) * 60000; const conflict = blocked.some(([start,end]) => minutes >= start && minutes <= end); return !tooSoon && !conflict; }); res.json({ date, day: dayKey, workingHours: hours, timezone: d.profile.timezone, slots }); });
app.get('/api/timezone/convert', (req, res) => { const time = String(req.query.time || ''); const from = Number(req.query.from); const to = Number(req.query.to); const m = time.match(/^(\d{1,2}):(\d{2})$/); if (!m || !Number.isFinite(from) || !Number.isFinite(to)) return res.status(400).json({ error: 'time, from, and to are required.' }); let minutes = Number(m[1]) * 60 + Number(m[2]) + (to - from) * 60; minutes = (minutes + 1440) % 1440; const h = String(Math.floor(minutes / 60)).padStart(2,'0'); const min = String(minutes % 60).padStart(2,'0'); res.json({ time, converted: `${h}:${min}`, from, to }); });
app.post('/api/integrations/google-calendar', requireAuth, (req, res) => { const d = readData(); d.integrations.googleCalendar = true; d.integrations.googleMeet = true; writeData(d); res.json({ ok: true, integrations: d.integrations }); });
app.post('/api/calendar/sync', requireAuth, (req, res) => { const provider = String(req.body?.provider || '').toLowerCase(); const allowed = ['google', 'outlook', 'apple']; if (!allowed.includes(provider)) return res.status(400).json({ error: 'Unsupported calendar provider.' }); const d = readData(); const key = provider === 'google' ? 'googleCalendar' : provider; d.integrations[key] = true; writeData(d); res.json({ ok: true, provider, syncedAt: new Date().toISOString(), conflicts: d.bookings.length ? 1 : 0 }); });
app.post('/api/meeting-types', requireAuth, (req, res) => { const d = readData(); const body = req.body || {}; const item = { id: Date.now().toString(), name: body.name || 'اجتماع جديد', en: body.en || 'New meeting', duration: Number(body.duration) || 30, color: body.color || '#2166f3', mode: body.mode || 'Google Meet' }; d.meetingTypes.push(item); writeData(d); res.status(201).json(item); });
app.post('/api/bookings', async (req, res) => { const d = config.useSupabase ? await supabaseState.publicState() : readData(); const b = req.body || {}; if (!b.name || !b.email || !b.date || !b.time || !b.meetingTypeId) return res.status(400).json({ error: 'Name, email, date, time, and meeting type are required.' }); if (bookingOutsideRules(d, b.date, b.time)) return res.status(409).json({ error: 'This time is outside the booking window.' }); const type = d.meetingTypes.find(x => x.id === b.meetingTypeId); if (bookingOverlaps(d, b.date, b.time, Number(type?.duration || 30))) return res.status(409).json({ error: 'This time overlaps another meeting.' }); if (config.useSupabase) { try { const profiles = await supabaseState.ownerProfile(); const owner = profiles?.id; if (!owner) return res.status(503).json({ error: 'No Supabase scheduling profile is configured.' }); const token = crypto.randomBytes(24).toString('hex'); const start = new Date(`${b.date}T${b.time}:00Z`); const end = new Date(start.getTime() + Number(type?.duration || 30) * 60000); const rows = await require('./supabase/client').insert('bookings', { owner_id: owner, meeting_type_id: type?.supabaseId || b.meetingTypeId, guest_name: b.name, guest_email: b.email, guest_timezone: b.timezone || null, starts_at: start.toISOString(), ends_at: end.toISOString(), notes: b.notes || null, status: 'confirmed', manage_token_hash: crypto.createHash('sha256').update(token).digest('hex') }); const row = rows[0]; return res.status(201).json({ id: row.id, ...b, manageToken: token, meetingType: type?.en || 'Meeting', status: row.status, createdAt: row.created_at }); } catch (error) { return res.status(503).json({ error: 'Unable to save booking to Supabase.', detail: error.message }); } } const booking = { id: Date.now().toString(), ...b, manageToken: crypto.randomBytes(24).toString('hex'), meetingType: type?.en || 'Meeting', status: 'confirmed', createdAt: new Date().toISOString() }; d.bookings.push(booking); d.notifications = d.notifications || []; d.notifications.push({ id: `booking-${booking.id}`, channel: 'in-app', recipient: 'host', type: 'booking-confirmed', bookingId: booking.id, message: `${booking.name} booked ${booking.meetingType} for ${booking.date} at ${booking.time}.`, status: 'unread', createdAt: booking.createdAt }); writeData(d); let calendarEvent = null; let calendarError = null; try { calendarEvent = await googleCalendarCreate(d.users?.[0]?.id, booking, type, d.profile?.timezone); } catch (error) { calendarError = error.message; } if (calendarEvent) { booking.googleEventId = calendarEvent.id; writeData(d); } res.status(201).json({ ...booking, calendar: calendarEvent ? { status: 'created', eventId: calendarEvent.id, htmlLink: calendarEvent.htmlLink || null } : { status: calendarError ? 'error' : 'not_connected', message: calendarError || 'Google Calendar is not connected.' } }); });
app.get('/api/bookings/:id/ics', (req, res) => { const d = readData(); const booking = d.bookings.find(x => x.id === req.params.id); if (!booking) return res.status(404).json({ error: 'Booking not found.' }); const sessionUser = sessions.get(cookieValue(req, 'calpro_session')); const token = req.headers['x-booking-token'] || req.query.token; if (!sessionUser && token !== booking.manageToken) return res.status(403).json({ error: 'A valid booking token or host login is required.' }); const type = d.meetingTypes.find(x => x.id === booking.meetingTypeId); const duration = Number(type?.duration || 30); const start = `${booking.date.replaceAll('-','')}T${booking.time.replace(':','')}00`; const startMinutes = Number(booking.time.slice(0,2))*60 + Number(booking.time.slice(3)) + duration; const end = `${booking.date.replaceAll('-','')}T${String(Math.floor(startMinutes/60)).padStart(2,'0')}${String(startMinutes%60).padStart(2,'0')}00`; const clean = value => String(value || '').replace(/[\\,;\n]/g, ' '); const ics = ['BEGIN:VCALENDAR','VERSION:2.0','PRODID:-//CalPro//Mawaeedy//EN','BEGIN:VEVENT',`UID:${booking.id}@calpro`,`DTSTAMP:${new Date().toISOString().replace(/[-:.]/g,'').replace(/\d{3}Z$/,'Z')}`,`DTSTART;TZID=${d.profile.timezone}:${start}`,`DTEND;TZID=${d.profile.timezone}:${end}`,`SUMMARY:${clean(booking.meetingType)}`,`DESCRIPTION:${clean(booking.notes || 'Scheduled with Mawaeedy')}`,`ORGANIZER:CN=${clean(d.profile.name)}`,`ATTENDEE;CN=${clean(booking.name)}:mailto:${clean(booking.email)}`,'END:VEVENT','END:VCALENDAR'].join('\r\n'); res.setHeader('Content-Type','text/calendar; charset=utf-8'); res.setHeader('Content-Disposition', `attachment; filename="calpro-${booking.id}.ics"`); res.send(ics); });
app.patch('/api/bookings/:id', async (req, res) => { const d = readData(); const booking = d.bookings.find(x => x.id === req.params.id); if (!booking) return res.status(404).json({ error: 'Booking not found.' }); const sessionUser = sessions.get(cookieValue(req, 'calpro_session')); if (!sessionUser && req.headers['x-booking-token'] !== booking.manageToken) return res.status(403).json({ error: 'A valid booking token or host login is required.' }); d.notifications = d.notifications || []; if (req.body?.status === 'cancelled') { booking.status = 'cancelled'; d.notifications.push({ id: `cancel-${booking.id}-${Date.now()}`, channel: 'in-app', recipient: 'host', type: 'booking-cancelled', bookingId: booking.id, message: `${booking.name} cancelled the ${booking.meetingType} on ${booking.date} at ${booking.time}.`, status: 'unread', createdAt: new Date().toISOString() }); writeData(d); if (booking.googleEventId) { try { await googleCalendarChange(d.users?.[0]?.id, booking.googleEventId, 'DELETE'); } catch {} } return res.json(booking); } if (req.body?.date || req.body?.time) { const date = req.body.date || booking.date; const time = req.body.time || booking.time; const type = d.meetingTypes.find(x => x.id === booking.meetingTypeId); if (bookingOverlaps(d, date, time, Number(type?.duration || 30), booking.id)) return res.status(409).json({ error: 'This time overlaps another meeting.' }); booking.date = date; booking.time = time; booking.status = 'rescheduled'; d.notifications.push({ id: `reschedule-${booking.id}-${Date.now()}`, channel: 'in-app', recipient: 'host', type: 'booking-rescheduled', bookingId: booking.id, message: `${booking.name} rescheduled to ${booking.date} at ${booking.time}.`, status: 'unread', createdAt: new Date().toISOString() }); writeData(d); return res.json(booking); } res.status(400).json({ error: 'Provide a new date/time or cancelled status.' }); });
if (require.main === module) app.listen(PORT, () => console.log(`CalPro running at http://localhost:${PORT}`));
module.exports = app;
